
item{
    id: 1
    name: 'cow/bull'
}

item{
    id: 2
    name: 'buffalo'
}

item{
    id: 3
    name: 'boar'
}

item{
    id: 4
    name: 'dog'
}

item{
    id: 5
    name: 'elephant'
}

item{
    id: 6
    name: 'goat'
}

item{
    id: 7
    name: 'leopard'
}

item{
    id: 8
    name: 'monkey'
}

item{
    id: 9
    name: 'snake'
}

item{
    id: 10
    name: 'tiger'
}

item{
    id: 11
    name: 'other'
}